# Generated by Django 2.0 on 2020-01-22 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masjid',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masjid',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
