# Generated by Django 2.0 on 2020-01-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masjids', '0001_initial'),
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=64, verbose_name='suggester name')),
                ('user_phone', models.CharField(blank=True, max_length=13, verbose_name='suggester phone')),
                ('name', models.CharField(max_length=256, verbose_name='Masjid Name')),
                ('address', models.TextField(blank=True)),
                ('fajar', models.TimeField(blank=True, null=True)),
                ('zuhar', models.TimeField(blank=True, null=True)),
                ('asar', models.TimeField(blank=True, null=True)),
                ('maghrib', models.TimeField(blank=True, null=True)),
                ('isha', models.TimeField(blank=True, null=True)),
                ('juma', models.TimeField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('suggested_on', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localities.Area')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajar', models.TimeField(blank=True, null=True)),
                ('zuhar', models.TimeField(blank=True, null=True)),
                ('asar', models.TimeField(blank=True, null=True)),
                ('maghrib', models.TimeField(blank=True, null=True)),
                ('isha', models.TimeField(blank=True, null=True)),
                ('juma', models.TimeField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('suggested_on', models.DateTimeField(auto_now_add=True)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjids.Masjid')),
            ],
        ),
    ]
