# Generated by Django 2.2 on 2020-01-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesuggestion',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='timesuggestion',
            name='user_phone',
        ),
    ]
